import { BackendTemplate } from '../types';

export const freshDenoTemplate: BackendTemplate = {
  id: 'fresh-deno',
  name: 'fresh-deno',
  displayName: 'Fresh (Deno)',
  description: 'Modern full-stack web framework for Deno with SSR and islands architecture',
  language: 'typescript',
  framework: 'fresh',
  version: '1.0.0',
  tags: ['deno', 'fresh', 'typescript', 'ssr', 'islands', 'pwa', 'full-stack'],
  port: 8000,
  dependencies: {},
  features: ['authentication', 'validation', 'logging', 'cors', 'documentation', 'ssr', 'islands'],

  files: {
    // Import map for Deno
    'import_map.json': `{
  "imports": {
    "fresh/": "https://deno.land/x/fresh@1.6.8/",
    "preact": "https://esm.sh/preact@10.19.6",
    "preact/": "https://esm.sh/preact@10.19.6/",
    "preact/hooks": "https://esm.sh/preact@10.19.6/hooks",
    "@preact/signals": "https://esm.sh/@preact/signals@1.2.1",
    "@preact/signals-core": "https://esm.sh/@preact/signals-core@1.5.0",
    "twind": "https://esm.sh/twind@0.16.19",
    "twind/": "https://esm.sh/twind@0.16.19/",
    "std/": "https://deno.land/std@0.208.0/"
  }
}
`,

    // Deno configuration
    'deno.json': `{
  "tasks": {
    "start": "deno run -A --watch=main.ts",
    "build": "deno run -A dev.ts",
    "update": "deno run -A -r https://fresh.deno.dev/update ."
  },
  "importMap": "./import_map.json",
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact"
  }
}
`,

    // Main entry point (auto-generated by Fresh)
    'main.ts': `/// <reference no-default-export="true" />
import { start } from "$fresh/server.ts";
import manifest from "./fresh.gen.ts";

import { config } from "./config.ts";
import { db } from "./db.ts";

// Initialize database
await db.initialize();

await start(manifest, { port: config.port });
`,

    // Fresh configuration
    'fresh.config.ts': `import { tailwind } from "twind";
import { defineConfig } from "$fresh/server.ts";

export default defineConfig({
  plugins: [tailwind()],
});
`,

    // Configuration
    'config.ts': `const config = {
  port: Number(Deno.env.get("PORT")) || 8000,
  environment: Deno.env.get("DENO_ENVIRONMENT") || "development",

  // JWT
  jwtSecret: Deno.env.get("JWT_SECRET") || "change-this-secret-in-production",
  jwtExpiration: Deno.env.get("JWT_EXPIRATION") || "7d",

  // Database
  dbPath: Deno.env.get("DB_PATH") || "./data/db.json",
};

export { config };
`,

    // Database (in-memory)
    'db.ts': `import { config } from "./config.ts";

interface User {
  id: string;
  email: string;
  password: string;
  name: string;
  role: "user" | "admin";
  createdAt: string;
  updatedAt: string;
}

interface Product {
  id: string;
  name: string;
  description?: string;
  price: number;
  stock: number;
  createdAt: string;
  updatedAt: string;
}

class InMemoryDatabase {
  private users: User[] = [];
  private products: Product[] = [];

  async initialize() {
    console.log("📦 Using in-memory database");

    // Create admin user
    const adminPassword = await this.hashPassword("admin123");
    this.users.push({
      id: crypto.randomUUID(),
      email: "admin@example.com",
      password: adminPassword,
      name: "Admin User",
      role: "admin",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });

    // Create sample products
    this.products.push(
      {
        id: "1",
        name: "Sample Product 1",
        description: "This is a sample product",
        price: 29.99,
        stock: 100,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "2",
        name: "Sample Product 2",
        description: "Another sample product",
        price: 49.99,
        stock: 50,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      }
    );

    console.log("✅ Database initialized");
    console.log("👤 Default admin: admin@example.com / admin123");
  }

  private async hashPassword(password: string): Promise<string> {
    const encoder = new TextEncoder();
    const data = encoder.encode(password);
    const hashBuffer = await crypto.subtle.digest("SHA-256", data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map(b => b.toString(16).padStart(2, "0")).join("");
  }

  private async comparePassword(password: string, hash: string): Promise<boolean> {
    const passwordHash = await this.hashPassword(password);
    return passwordHash === hash;
  }

  // Users
  getUsers(): User[] {
    return this.users.map(u => ({ ...u, password: "" }));
  }

  getUserById(id: string): User | undefined {
    const user = this.users.find(u => u.id === id);
    return user ? { ...user, password: "" } : undefined;
  }

  getUserByEmail(email: string): User | undefined {
    return this.users.find(u => u.email === email);
  }

  async createUser(user: Omit<User, "id" | "createdAt" | "updatedAt">): Promise<User> {
    const hashedPassword = await this.hashPassword(user.password);
    const newUser: User = {
      ...user,
      password: hashedPassword,
      id: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    this.users.push(newUser);
    return { ...newUser, password: "" };
  }

  async verifyUser(email: string, password: string): Promise<User | null> {
    const user = this.users.find(u => u.email === email);
    if (!user) return null;
    const valid = await this.comparePassword(password, user.password);
    if (!valid) return null;
    return { ...user, password: "" };
  }

  updateUser(id: string, updates: Partial<Omit<User, "id" | "createdAt" | "password">>): User | undefined {
    const index = this.users.findIndex(u => u.id === id);
    if (index === -1) return undefined;

    this.users[index] = {
      ...this.users[index],
      ...updates,
      updatedAt: new Date().toISOString(),
    };
    return { ...this.users[index], password: "" };
  }

  deleteUser(id: string): boolean {
    const index = this.users.findIndex(u => u.id === id);
    if (index === -1) return false;
    this.users.splice(index, 1);
    return true;
  }

  // Products
  getProducts(): Product[] {
    return this.products;
  }

  getProductById(id: string): Product | undefined {
    return this.products.find(p => p.id === id);
  }

  createProduct(product: Omit<Product, "id" | "createdAt" | "updatedAt">): Product {
    const newProduct: Product = {
      ...product,
      id: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    this.products.push(newProduct);
    return newProduct;
  }

  updateProduct(id: string, updates: Partial<Omit<Product, "id" | "createdAt">>): Product | undefined {
    const index = this.products.findIndex(p => p.id === id);
    if (index === -1) return undefined;

    this.products[index] = {
      ...this.products[index],
      ...updates,
      updatedAt: new Date().toISOString(),
    };
    return this.products[index];
  }

  deleteProduct(id: string): boolean {
    const index = this.products.findIndex(p => p.id === id);
    if (index === -1) return false;
    this.products.splice(index, 1);
    return true;
  }
}

export const db = new InMemoryDatabase();
`,

    // JWT utilities
    'utils/jwt.ts': `import { config } from "../config.ts";

export interface JWTPayload {
  sub: string;
  email: string;
  role: string;
  exp?: number;
}

export async function createToken(payload: Omit<JWTPayload, "exp">): Promise<string> {
  const expiration = Math.floor(Date.now() / 1000) + (7 * 24 * 60 * 60); // 7 days
  const header = { alg: "HS256", typ: "JWT" };
  const tokenPayload = { ...payload, exp: expiration };

  const encoder = new TextEncoder();
  const secretKey = await crypto.subtle.importKey(
    "raw",
    encoder.encode(config.jwtSecret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );

  const headerEncoded = btoa(JSON.stringify(header)).replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_");
  const payloadEncoded = btoa(JSON.stringify(tokenPayload)).replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_");

  const data = \`\${headerEncoded}.\${payloadEncoded}\`;
  const signature = await crypto.subtle.sign(
    "HMAC",
    secretKey,
    encoder.encode(data)
  );

  const signatureEncoded = btoa(String.fromCharCode(...new Uint8Array(signature)))
    .replace(/=/g, "")
    .replace(/\+/g, "-")
    .replace(/\//g, "_");

  return \`\${data}.\${signatureEncoded}\`;
}

export async function verifyToken(token: string): Promise<JWTPayload | null> {
  try {
    const parts = token.split(".");
    if (parts.length !== 3) return null;

    const [headerEncoded, payloadEncoded, signatureEncoded] = parts;
    const data = \`\${headerEncoded}.\${payloadEncoded}\`;

    const encoder = new TextEncoder();
    const secretKey = await crypto.subtle.importKey(
      "raw",
      encoder.encode(config.jwtSecret),
      { name: "HMAC", hash: "SHA-256" },
      false,
      ["verify"]
    );

    const signature = Uint8Array.from(atob(signatureEncoded.replace(/-/g, "+").replace(/_/g, "/")), c => c.charCodeAt(0));
    const valid = await crypto.subtle.verify(
      "HMAC",
      secretKey,
      signature,
      encoder.encode(data)
    );

    if (!valid) return null;

    const payload = JSON.parse(atob(payloadEncoded.replace(/-/g, "+").replace(/_/g, "/")));

    // Check expiration
    if (payload.exp && payload.exp < Math.floor(Date.now() / 1000)) {
      return null;
    }

    return payload;
  } catch {
    return null;
  }
}
`,

    // Middleware
    'middleware/auth.ts': `import { MiddlewareHandler } from "$fresh/server.ts";
import type { Context } from "$fresh/server.ts";
import { verifyToken, type JWTPayload } from "../utils/jwt.ts";

export interface AuthState {
  user: JWTPayload | null;
}

export const handler: MiddlewareHandler<AuthState> = async (req, ctx) => {
  const authHeader = req.headers.get("Authorization");

  if (!authHeader || !authHeader.startsWith("Bearer ")) {
    return ctx.next({ user: null });
  }

  const token = authHeader.substring(7);
  const payload = await verifyToken(token);

  return ctx.next({ user: payload || null });
};

export function requireAuth() {
  return async (req: Request, ctx: Context<AuthState>) => {
    if (!ctx.state.user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { "Content-Type": "application/json" },
      });
    }
    return ctx.next();
  };
}

export function requireRole(...roles: string[]) {
  return async (req: Request, ctx: Context<AuthState>) => {
    if (!ctx.state.user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { "Content-Type": "application/json" },
      });
    }
    if (!roles.includes(ctx.state.user.role)) {
      return new Response(JSON.stringify({ error: "Forbidden" }), {
        status: 403,
        headers: { "Content-Type": "application/json" },
      });
    }
    return ctx.next();
  };
}
`,

    // Routes - API: Auth
    'routes/api/auth.ts': `import { HandlerContext } from "$fresh/server.ts";
import { db } from "../../db.ts";
import { createToken } from "../../utils/jwt.ts";
import type { AuthState } from "../../middleware/auth.ts";

export const handler = {
  async POST(req: Request, ctx: HandlerContext<undefined, AuthState>) {
    const url = new URL(req.url);
    const action = url.pathname.split("/").pop();

    if (action === "login") {
      return handleLogin(req);
    } else if (action === "register") {
      return handleRegister(req);
    }

    return new Response("Not Found", { status: 404 });
  },
};

async function handleLogin(req: Request) {
  try {
    const body = await req.json();
    const { email, password } = body;

    if (!email || !password) {
      return new Response(JSON.stringify({ error: "Email and password required" }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }

    const user = await db.verifyUser(email, password);
    if (!user) {
      return new Response(JSON.stringify({ error: "Invalid credentials" }), {
        status: 401,
        headers: { "Content-Type": "application/json" },
      });
    }

    const token = await createToken({
      sub: user.id,
      email: user.email,
      role: user.role,
    });

    return new Response(JSON.stringify({
      token,
      user: {
        id: user.id,
        email: user.email,
        name: user.name,
        role: user.role,
      },
    }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (error) {
    return new Response(JSON.stringify({ error: "Invalid request" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }
}

async function handleRegister(req: Request) {
  try {
    const body = await req.json();
    const { email, password, name } = body;

    if (!email || !password || !name) {
      return new Response(JSON.stringify({ error: "Email, password, and name required" }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }

    if (password.length < 6) {
      return new Response(JSON.stringify({ error: "Password must be at least 6 characters" }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }

    const existingUser = db.getUserByEmail(email);
    if (existingUser) {
      return new Response(JSON.stringify({ error: "Email already registered" }), {
        status: 409,
        headers: { "Content-Type": "application/json" },
      });
    }

    const user = await db.createUser({
      email,
      password,
      name,
      role: "user",
    });

    const token = await createToken({
      sub: user.id,
      email: user.email,
      role: user.role,
    });

    return new Response(JSON.stringify({
      token,
      user: {
        id: user.id,
        email: user.email,
        name: user.name,
        role: user.role,
      },
    }), {
      status: 201,
      headers: { "Content-Type": "application/json" },
    });
  } catch (error) {
    return new Response(JSON.stringify({ error: "Invalid request" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }
}
`,

    // Routes - API: Products
    'routes/api/products.ts': `import { HandlerContext } from "$fresh/server.ts";
import { db } from "../../db.ts";
import type { AuthState } from "../../middleware/auth.ts";
import { requireAuth, requireRole } from "../../middleware/auth.ts";

export const handler = {
  async GET(req: Request, ctx: HandlerContext<undefined, AuthState>) {
    const url = new URL(req.url);
    const id = url.pathname.split("/").pop();

    if (id && id !== "products") {
      // Get single product
      const product = db.getProductById(id);
      if (!product) {
        return new Response(JSON.stringify({ error: "Product not found" }), {
          status: 404,
          headers: { "Content-Type": "application/json" },
        });
      }
      return new Response(JSON.stringify({ product }), {
        headers: { "Content-Type": "application/json" },
      });
    }

    // List all products
    const products = db.getProducts();
    return new Response(JSON.stringify({ products, count: products.length }), {
      headers: { "Content-Type": "application/json" },
    });
  },

  async POST(req: Request, ctx: HandlerContext<undefined, AuthState>) {
    return requireRole("admin")(req, ctx);
  },
};

export const handlerWithAuth = requireAuth()(async (req: Request, ctx: HandlerContext<undefined, AuthState>) => {
  const url = new URL(req.url);
  const id = url.pathname.split("/").pop();

  if (req.method === "POST") {
    const body = await req.json();
    const { name, description, price, stock } = body;

    const product = db.createProduct({
      name,
      description,
      price: Number(price),
      stock: Number(stock) || 0,
    });

    return new Response(JSON.stringify({ product }), {
      status: 201,
      headers: { "Content-Type": "application/json" },
    });
  }

  if (req.method === "PUT") {
    const body = await req.json();
    const product = db.updateProduct(id, body);

    if (!product) {
      return new Response(JSON.stringify({ error: "Product not found" }), {
        status: 404,
        headers: { "Content-Type": "application/json" },
      });
    }

    return new Response(JSON.stringify({ product }), {
      headers: { "Content-Type": "application/json" },
    });
  }

  if (req.method === "DELETE") {
    const deleted = db.deleteProduct(id);
    if (!deleted) {
      return new Response(JSON.stringify({ error: "Product not found" }), {
        status: 404,
        headers: { "Content-Type": "application/json" },
      });
    }
    return new Response(null, { status: 204 });
  }

  return new Response("Method Not Allowed", { status: 405 });
});
`,

    // Routes - API: Users
    'routes/api/users.ts': `import { HandlerContext } from "$fresh/server.ts";
import { db } from "../../db.ts";
import type { AuthState } from "../../middleware/auth.ts";
import { requireAuth, requireRole } from "../../middleware/auth.ts";

export const handler = {
  GET: (req: Request, ctx: HandlerContext<undefined, AuthState>) => {
    return requireRole("admin")(req, ctx);
  },
};

export const handlerWithAuth = requireAuth()(async (req: Request, ctx: HandlerContext<undefined, AuthState>) => {
  const url = new URL(req.url);
  const userId = ctx.state.user!.sub;

  if (url.pathname.endsWith("/me")) {
    const user = db.getUserById(userId);
    if (!user) {
      return new Response(JSON.stringify({ error: "User not found" }), {
        status: 404,
        headers: { "Content-Type": "application/json" },
      });
    }
    return new Response(JSON.stringify({ user }), {
      headers: { "Content-Type": "application/json" },
    });
  }

  // List all users (admin only)
  const users = db.getUsers();
  return new Response(JSON.stringify({ users, count: users.length }), {
    headers: { "Content-Type": "application/json" },
  });
});
`,

    // Routes - Health
    'routes/api/health.ts': `export const handler = () => {
  return new Response(JSON.stringify({
    status: "healthy",
    timestamp: new Date().toISOString(),
  }), {
    headers: { "Content-Type": "application/json" },
  });
};
`,

    // Islands - Counter component
    'islands/Counter.tsx': `import { signal } from "@preact/signals";

export default function Counter() {
  const count = signal(0);

  return (
    <div class="flex items-center gap-4">
      <button
        class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
        onClick={() => count.value--}
      >
        -1
      </button>
      <span class="text-2xl font-bold">{count}</span>
      <button
        class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
        onClick={() => count.value++}
      >
        +1
      </button>
    </div>
  );
}
`,

    // Routes - Home page
    'routes/index.tsx': `import Counter from "../islands/Counter.tsx";

export default function Home() {
  return (
    <main class="min-h-screen bg-gray-50">
      <div class="max-w-4xl mx-auto px-4 py-8">
        <h1 class="text-4xl font-bold text-gray-900 mb-4">
          Welcome to {{projectName}}
        </h1>
        <p class="text-lg text-gray-600 mb-8">
          A modern full-stack application built with Fresh and Deno
        </p>

        <div class="bg-white rounded-lg shadow-md p-6 mb-8">
          <h2 class="text-2xl font-semibold mb-4">Interactive Counter</h2>
          <p class="text-gray-600 mb-4">
            This is a Preact island with client-side interactivity
          </p>
          <Counter />
        </div>

        <div class="grid md:grid-cols-2 gap-6">
          <div class="bg-white rounded-lg shadow-md p-6">
            <h3 class="text-xl font-semibold mb-2">🚀 Fresh Framework</h3>
            <p class="text-gray-600">
              Modern full-stack framework with SSR and islands architecture
            </p>
          </div>

          <div class="bg-white rounded-lg shadow-md p-6">
            <h3 class="text-xl font-semibold mb-2">⚡ Deno Runtime</h3>
            <p class="text-gray-600">
              Secure, fast JavaScript/TypeScript runtime
            </p>
          </div>

          <div class="bg-white rounded-lg shadow-md p-6">
            <h3 class="text-xl font-semibold mb-2">🏝️ Islands Architecture</h3>
            <p class="text-gray-600">
              Progressive enhancement with zero JS by default
            </p>
          </div>

          <div class="bg-white rounded-lg shadow-md p-6">
            <h3 class="text-xl font-semibold mb-2">🎨 Tailwind CSS</h3>
            <p class="text-gray-600">
              Utility-first CSS framework for rapid UI development
            </p>
          </div>
        </div>

        <div class="mt-8 bg-blue-50 rounded-lg p-6">
          <h3 class="text-xl font-semibold mb-2">📚 API Endpoints</h3>
          <ul class="list-disc list-inside text-gray-700 space-y-1">
            <li>GET /api/health - Health check</li>
            <li>POST /api/auth/register - Register user</li>
            <li>POST /api/auth/login - Login user</li>
            <li>GET /api/products - List products</li>
            <li>GET /api/users/me - Get current user (auth required)</li>
          </ul>
        </div>
      </div>
    </main>
  );
}
`,

    // Environment file
    '.env.example': `# Server
PORT=8000
DENO_ENVIRONMENT=development

# JWT
JWT_SECRET=change-this-secret-in-production
JWT_EXPIRATION=7d

# Database
DB_PATH=./data/db.json
`,

    // Dockerfile
    'Dockerfile': `FROM denoland/deno:1.40.0

WORKDIR /app

# Cache dependencies
COPY deno.json import_map.json ./
RUN deno install

# Copy source
COPY . .

EXPOSE 8000

CMD ["deno", "task", "start"]
`,

    // Docker Compose
    'docker-compose.yml': `version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - JWT_SECRET=change-this-secret
      - DENO_ENVIRONMENT=production
    restart: unless-stopped
`,

    // Tests
    'tests/main_test.ts': `import { assertEquals, assertExists } from "$std/assert/mod.ts";
import { db } from "../db.ts";

Deno.test("Database initialization", async () => {
  await db.initialize();

  const users = db.getUsers();
  assertExists(users);
  assertEquals(users.length > 0, true);
});

Deno.test("User authentication", async () => {
  await db.initialize();

  const user = await db.verifyUser("admin@example.com", "admin123");
  assertExists(user);
  assertEquals(user.email, "admin@example.com");
  assertEquals(user.role, "admin");
});

Deno.test("Product management", async () => {
  await db.initialize();

  const products = db.getProducts();
  assertExists(products);
  assertEquals(products.length > 0, true);
});
`,

    // README
    'README.md': `# {{projectName}}

A modern full-stack web application built with Fresh framework on Deno runtime with SSR and islands architecture.

## Features

- **Fresh Framework**: Modern full-stack framework with edge-first architecture
- **Deno Runtime**: Secure, fast JavaScript/TypeScript runtime
- **SSR + Islands**: Server-side rendering with progressive enhancement
- **Preact**: Fast 3kB React alternative
- **Tailwind CSS**: Utility-first CSS framework
- **JWT Authentication**: Token-based authentication
- **In-Memory Database**: Simple, fast data persistence
- **Docker Support**: Containerized deployment

## Requirements

- Deno 1.40+

## Quick Start

1. Clone and navigate to the project:
   \`\`\`bash
   cd {{projectName}}
   \`\`\`

2. Start the development server:
   \`\`\`bash
   deno task start
   \`\`\`

3. Visit http://localhost:8000

## Available Scripts

\`\`\`bash
deno task start      # Start dev server with hot reload
deno task build      # Build for production
deno task update     # Update Fresh dependencies
\`\`\`

## API Endpoints

### Health
- \`GET /api/health\` - Health check

### Authentication
- \`POST /api/auth/register\` - Register new user
- \`POST /api/auth/login\` - Login user

### Products
- \`GET /api/products\` - List all products
- \`GET /api/products/:id\` - Get product by ID
- \`POST /api/products\` - Create product (admin only)
- \`PUT /api/products/:id\` - Update product (admin only)
- \`DELETE /api/products/:id\` - Delete product (admin only)

### Users
- \`GET /api/users/me\` - Get current user (auth required)
- \`GET /api/users\` - List all users (admin only)

## Default Credentials

- Email: \`admin@example.com\`
- Password: \`admin123\`

## Project Structure

\`\`\`
├── islands/           # Client-side islands
├── routes/            # File-based routing
│   ├── api/          # API endpoints
│   └── index.tsx     # Home page
├── middleware/        # Server middleware
├── utils/             # Utilities
├── db.ts             # Database layer
├── config.ts         # Configuration
└── main.ts           # Entry point
\`\`\`

## What is Fresh?

Fresh is a modern web framework that provides:
- **Edge-first**: Deploy anywhere with Deno Deploy
- **Islands Architecture**: Zero JS by default, opt-in interactivity
- **No Build Step**: No bundling or compilation needed
- **Type-Safe**: Full TypeScript support
- **Fast**: Sub-millisecond cold starts

## Islands Architecture

Fresh uses islands architecture where:
- Most of the page is server-rendered (no JS sent to client)
- Interactive parts are "islands" that hydrate independently
- Better performance and progressive enhancement

## Docker

Build and run with Docker:

\`\`\`bash
docker build -t {{projectName}} .
docker run -p 8000:8000 {{projectName}}
\`\`\`

Or use Docker Compose:

\`\`\`bash
docker-compose up
\`\`\`

## License

MIT
`
  }
};
