// Auto-generated Unified License Compliance Checker
// Generated at: 2026-01-12T22:00:00.000Z

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

interface LicenseInfo {
  packageName: string;
  version: string;
  license: string;
  licenseType: 'permissive' | 'copyleft' | 'proprietary' | 'unknown';
  risk: 'allowed' | 'review-required' | 'forbidden';
}

interface CompliancePolicy {
  allowedLicenses: string[];
  forbiddenLicenses: string[];
  reviewRequiredLicenses: string[];
  allowPermissive: boolean;
  allowCopyleft: boolean;
}

interface ComplianceResult {
  language: string;
  totalPackages: number;
  compliant: number;
  nonCompliant: number;
  reviewRequired: number;
  violations: LicenseInfo[];
  timestamp: string;
}

export function displayConfig(config: any): void {
  console.log('\x1b[36m%s\x1b[0m', '✨ Unified License Compliance Checker');
  console.log('\x1b[90m%s\x1b[0m', '────────────────────────────────────────────────────────────');
  console.log('\x1b[33m%s\x1b[0m', 'Project Name:', config.projectName);
  console.log('\x1b[33m%s\x1b[0m', 'Auto-Fix:', config.enableAutoFix ? 'Enabled' : 'Disabled');
  console.log('\x1b[33m%s\x1b[0m', 'Policy File:', config.policyFile || 'default');
  console.log('\x1b[90m%s\x1b[0m', '────────────────────────────────────────────────────────────\n');
}

export function generateLicenseMD(config: any): string {
  let md = '# License Compliance Checker\n\n';
  md += '## Features\n\n';
  md += '- Cross-ecosystem license detection\n';
  md += '- Policy-based compliance checking\n';
  md += '- Automatic violation detection\n';
  md += '- License categorization (permissive, copyleft, proprietary)\n';
  md += '- Support for: npm, pip, cargo, maven, gradle, composer\n\n';
  md += '## Usage\n\n';
  md += '### TypeScript/JavaScript\n';
  md += '```typescript\n';
  md += 'import checker from \'./license-compliance\';\n\n';
  md += '// Check compliance\n';
  md += 'const results = await checker.checkCompliance();\n\n';
  md += '// Generate report\n';
  md += 'await checker.generateReport(results);\n\n';
  md += '// Fix violations\n';
  md += 'await checker.fixViolations(results);\n';
  md += '```\n\n';
  md += '### Python\n';
  md += '```python\n';
  md += 'from license_compliance import checker\n\n';
  md += '# Check compliance\n';
  md += 'results = await checker.check_compliance()\n\n';
  md += '# Generate report\n';
  md += 'await checker.generate_report(results)\n';
  md += '```\n\n';
  return md;
}

export function generateTypeScriptLicense(config: any): string {
  let code = '// Auto-generated License Compliance Checker for ' + config.projectName + '\n';
  code += '// Generated at: ' + new Date().toISOString() + '\n\n';
  code += 'import { execSync } from \'child_process\';\n';
  code += 'import fs from \'fs\';\n';
  code += 'import path from \'path\';\n\n';
  code += 'interface LicenseInfo {\n';
  code += '  packageName: string;\n';
  code += '  version: string;\n';
  code += '  license: string;\n';
  code += '  licenseType: \'permissive\' | \'copyleft\' | \'proprietary\' | \'unknown\';\n';
  code += '  risk: \'allowed\' | \'review-required\' | \'forbidden\';\n';
  code += '}\n\n';
  code += 'interface CompliancePolicy {\n';
  code += '  allowedLicenses: string[];\n';
  code += '  forbiddenLicenses: string[];\n';
  code += '  reviewRequiredLicenses: string[];\n';
  code += '  allowPermissive: boolean;\n';
  code += '  allowCopyleft: boolean;\n';
  code += '}\n\n';
  code += 'interface ComplianceResult {\n';
  code += '  language: string;\n';
  code += '  totalPackages: number;\n';
  code += '  compliant: number;\n';
  code += '  nonCompliant: number;\n';
  code += '  reviewRequired: number;\n';
  code += '  violations: LicenseInfo[];\n';
  code += '  timestamp: string;\n';
  code += '}\n\n';
  code += 'class LicenseComplianceChecker {\n';
  code += '  private projectRoot: string;\n';
  code += '  private policy: CompliancePolicy;\n';
  code += '  private enableAutoFix: boolean;\n\n';
  code += '  constructor(options: any = {}) {\n';
  code += '    this.projectRoot = options.projectRoot || process.cwd();\n';
  code += '    this.policy = options.policy || this.getDefaultPolicy();\n';
  code += '    this.enableAutoFix = options.enableAutoFix || false;\n';
  code += '  }\n\n';
  code += '  async checkCompliance(): Promise<ComplianceResult[]> {\n';
  code += '    console.log(\'[License] Checking license compliance...\');\n';
  code += '    const results: ComplianceResult[] = [];\n\n';
  code += '    // Check npm packages\n';
  code += '    if (fs.existsSync(path.join(this.projectRoot, \'package.json\'))) {\n';
  code += '      const npmResult = await this.checkNpm();\n';
  code += '      if (npmResult) results.push(npmResult);\n';
  code += '    }\n\n';
  code += '    // Check Python packages\n';
  code += '    if (fs.existsSync(path.join(this.projectRoot, \'requirements.txt\')) ||\n';
  code += '        fs.existsSync(path.join(this.projectRoot, \'pyproject.toml\'))) {\n';
  code += '      const pipResult = await this.checkPip();\n';
  code += '      if (pipResult) results.push(pipResult);\n';
  code += '    }\n\n';
  code += '    // Check Rust packages\n';
  code += '    if (fs.existsSync(path.join(this.projectRoot, \'Cargo.toml\'))) {\n';
  code += '      const cargoResult = await this.checkCargo();\n';
  code += '      if (cargoResult) results.push(cargoResult);\n';
  code += '    }\n\n';
  code += '    console.log(\'[License] Compliance check complete\');\n';
  code += '    return results;\n';
  code += '  }\n\n';
  code += '  private async checkNpm(): Promise<ComplianceResult | null> {\n';
  code += '    try {\n';
  code += '      console.log(\'[License] Checking npm packages...\');\n';
  code += '      const licenses = await this.getNpmLicenses();\n';
  code += '      return this.evaluateCompliance(licenses, \'javascript\');\n';
  code += '    } catch (error: any) {\n';
  code += '      console.error(\'[License] Failed to check npm licenses:\', error.message);\n';
  code += '      return null;\n';
  code += '    }\n';
  code += '  }\n\n';
  code += '  private async getNpmLicenses(): Promise<LicenseInfo[]> {\n';
  code += '    const licenses: LicenseInfo[] = [];\n\n';
  code += '    try {\n';
  code += '      const output = execSync(\'npm ls --json --depth=0\', {\n';
  code += '        cwd: this.projectRoot,\n';
  code += '        encoding: \'utf-8\',\n';
  code += '        stdio: \'pipe\',\n';
  code += '      });\n';
  code += '      const data = JSON.parse(output);\n';
  code += '      const deps = data.dependencies || {};\n\n';
  code += '      for (const [name, info]: Object.entries(deps)) {\n';
  code += '        const pkg = info as any;\n';
  code += '        licenses.push({\n';
  code += '          packageName: name,\n';
  code += '          version: pkg.version,\n';
  code += '          license: this.extractLicense(pkg),\n';
  code += '          licenseType: this.categorizeLicense(this.extractLicense(pkg)),\n';
  code += '          risk: \'allowed\',\n';
  code += '        });\n';
  code += '      }\n';
  code += '    } catch (error: any) {\n';
  code += '      // Fallback: parse package.json directly\n';
  code += '      const pkgPath = path.join(this.projectRoot, \'package.json\');\n';
  code += '      if (fs.existsSync(pkgPath)) {\n';
  code += '        const pkg = JSON.parse(fs.readFileSync(pkgPath, \'utf-8\'));\n';
  code += '        const deps = { ...pkg.dependencies, ...pkg.devDependencies };\n';
  code += '        for (const [name] of Object.entries(deps)) {\n';
  code += '          licenses.push({\n';
  code += '            packageName: name,\n';
  code += '            version: \'unknown\',\n';
  code += '            license: \'unknown\',\n';
  code += '            licenseType: \'unknown\',\n';
  code += '            risk: \'review-required\',\n';
  code += '          });\n';
  code += '        }\n';
  code += '      }\n';
  code += '    }\n\n';
  code += '    return licenses;\n';
  code += '  }\n\n';
  code += '  private extractLicense(pkg: any): string {\n';
  code += '    if (pkg.license) return typeof pkg.license === \'string\' ? pkg.license : \'unknown\';\n';
  code += '    if (pkg.licenses && Array.isArray(pkg.licenses)) {\n';
  code += '      return pkg.licenses.map((l: any) => l.type || l).join(\' OR \');\n';
  code += '    }\n';
  code += '    return \'unknown\';\n';
  code += '  }\n\n';
  code += '  private categorizeLicense(license: string): \'permissive\' | \'copyleft\' | \'proprietary\' | \'unknown\' {\n';
  code += '    const l = license.toLowerCase();\n';
  code += '    const permissive = [\'mit\', \'apache\', \'bsd\', \'isc\', \'unlicense\'];\n';
  code += '    const copyleft = [\'gpl\', \'lgpl\', \'agpl\', \'mpl\', \'cddl\', \'epl\'];\n\n';
  code += '    if (permissive.some(p => l.includes(p))) return \'permissive\';\n';
  code += '    if (copyleft.some(c => l.includes(c))) return \'copyleft\';\n';
  code += '    if (l.includes(\'proprietary\') || l.includes(\'commercial\')) return \'proprietary\';\n';
  code += '    return \'unknown\';\n';
  code += '  }\n\n';
  code += '  private async checkPip(): Promise<ComplianceResult | null> {\n';
  code += '    try {\n';
  code += '      console.log(\'[License] Checking Python packages...\');\n';
  code += '      const licenses = await this.getPipLicenses();\n';
  code += '      return this.evaluateCompliance(licenses, \'python\');\n';
  code += '    } catch (error: any) {\n';
  code += '      console.error(\'[License] Failed to check pip licenses:\', error.message);\n';
  code += '      return null;\n';
  code += '    }\n';
  code += '  }\n\n';
  code += '  private async getPipLicenses(): Promise<LicenseInfo[]> {\n';
  code += '    const licenses: LicenseInfo[] = [];\n';
  code += '    const reqPath = path.join(this.projectRoot, \'requirements.txt\');\n\n';
  code += '    if (!fs.existsSync(reqPath)) return licenses;\n\n';
  code += '    const content = fs.readFileSync(reqPath, \'utf-8\');\n';
  code += '    const lines = content.split(\'\\n\').filter(l => l.trim() && !l.startsWith(\'#\'));\n\n';
  code += '    for (const line of lines) {\n';
  code += '      const match = line.match(/^([a-zA-Z0-9_-]+)(==|>=|<=)(.+)$/);\n';
  code += '      if (match) {\n';
  code += '        const [, name, , version] = match;\n';
  code += '        licenses.push({\n';
  code += '          packageName: name,\n';
  code += '          version,\n';
  code += '          license: \'unknown\',\n';
  code += '          licenseType: \'unknown\',\n';
  code += '          risk: \'review-required\',\n';
  code += '        });\n';
  code += '      }\n';
  code += '    }\n\n';
  code += '    return licenses;\n';
  code += '  }\n\n';
  code += '  private async checkCargo(): Promise<ComplianceResult | null> {\n';
  code += '    try {\n';
  code += '      console.log(\'[License] Checking Rust packages...\');\n';
  code += '      const licenses = await this.getCargoLicenses();\n';
  code += '      return this.evaluateCompliance(licenses, \'rust\');\n';
  code += '    } catch (error: any) {\n';
  code += '      console.error(\'[License] Failed to check cargo licenses:\', error.message);\n';
  code += '      return null;\n';
  code += '    }\n';
  code += '  }\n\n';
  code += '  private async getCargoLicenses(): Promise<LicenseInfo[]> {\n';
  code += '    const licenses: LicenseInfo[] = [];\n';
  code += '    const cargoPath = path.join(this.projectRoot, \'Cargo.toml\');\n\n';
  code += '    if (!fs.existsSync(cargoPath)) return licenses;\n\n';
  code += '    const content = fs.readFileSync(cargoPath, \'utf-8\');\n';
  code += '    const depsMatch = content.match(/\\[dependencies\\]([\\s\\S]*?)(?=\n\\[|$)/);\n\n';
  code += '    if (depsMatch) {\n';
  code += '      const deps = depsMatch[1];\n';
  code += '      const lines = deps.split(\'\\n\').filter(l => l.includes(\'=\'));\n\n';
  code += '      for (const line of lines) {\n';
  code += '        const match = line.match(/^([a-zA-Z0-9_-]+)\\s*=\\s*"(.+)"/);\n';
  code += '        if (match) {\n';
  code += '          const [, name, version] = match;\n';
  code += '          licenses.push({\n';
  code += '            packageName: name,\n';
  code += '            version,\n';
  code += '            license: \'unknown\',\n';
  code += '            licenseType: \'unknown\',\n';
  code += '            risk: \'review-required\',\n';
  code += '          });\n';
  code += '        }\n';
  code += '      }\n';
  code += '    }\n\n';
  code += '    return licenses;\n';
  code += '  }\n\n';
  code += '  private evaluateCompliance(licenses: LicenseInfo[], language: string): ComplianceResult {\n';
  code += '    const violations: LicenseInfo[] = [];\n';
  code += '    let compliant = 0;\n';
  code += '    let reviewRequired = 0;\n\n';
  code += '    for (const lic of licenses) {\n';
  code += '      lic.risk = this.assessRisk(lic);\n';
  code += '      if (lic.risk === \'forbidden\') {\n';
  code += '        violations.push(lic);\n';
  code += '      } else if (lic.risk === \'review-required\') {\n';
  code += '        reviewRequired++;\n';
  code += '      } else {\n';
  code += '        compliant++;\n';
  code += '      }\n';
  code += '    }\n\n';
  code += '    return {\n';
  code += '      language,\n';
  code += '      totalPackages: licenses.length,\n';
  code += '      compliant,\n';
  code += '      nonCompliant: violations.length,\n';
  code += '      reviewRequired,\n';
  code += '      violations,\n';
  code += '      timestamp: new Date().toISOString(),\n';
  code += '    };\n';
  code += '  }\n\n';
  code += '  private assessRisk(lic: LicenseInfo): \'allowed\' | \'review-required\' | \'forbidden\' {\n';
  code += '    const license = lic.license.toLowerCase();\n\n';
  code += '    // Check forbidden licenses\n';
  code += '    for (const forbidden of this.policy.forbiddenLicenses) {\n';
  code += '      if (license.includes(forbidden.toLowerCase())) {\n';
  code += '        return \'forbidden\';\n';
  code += '      }\n';
  code += '    }\n\n';
  code += '    // Check review-required licenses\n';
  code += '    for (const review of this.policy.reviewRequiredLicenses) {\n';
  code += '      if (license.includes(review.toLowerCase())) {\n';
  code += '        return \'review-required\';\n';
  code += '      }\n';
  code += '    }\n\n';
  code += '    // Check by license type\n';
  code += '    if (lic.licenseType === \'copyleft\' && !this.policy.allowCopyleft) {\n';
  code += '      return \'review-required\';\n';
  code += '    }\n\n';
  code += '    if (lic.licenseType === \'unknown\') {\n';
  code += '      return \'review-required\';\n';
  code += '    }\n\n';
  code += '    return \'allowed\';\n';
  code += '  }\n\n';
  code += '  async fixViolations(results: ComplianceResult[]): Promise<void> {\n';
  code += '    if (!this.enableAutoFix) {\n';
  code += '      console.log(\'[License] Auto-fix is disabled\');\n';
  code += '      return;\n';
  code += '    }\n\n';
  code += '    console.log(\'[License] Cannot automatically fix license violations\');\n';
  code += '    console.log(\'[License] Please manually review and replace forbidden packages\');\n';
  code += '  }\n\n';
  code += '  async generateReport(results: ComplianceResult[]): Promise<void> {\n';
  code += '    console.log(\'[License] Generating compliance report...\');\n\n';
  code += '    const reportPath = path.join(this.projectRoot, \'license-compliance-report.json\');\n';
  code += '    fs.writeFileSync(reportPath, JSON.stringify(results, null, 2));\n\n';
  code += '    const mdReport = this.generateMarkdownReport(results);\n';
  code += '    const mdPath = path.join(this.projectRoot, \'license-compliance-report.md\');\n';
  code += '    fs.writeFileSync(mdPath, mdReport);\n\n';
  code += '    console.log(\'[License] Report saved to\', reportPath);\n';
  code += '  }\n\n';
  code += '  private generateMarkdownReport(results: ComplianceResult[]): string {\n';
  code += '    let md = \'# License Compliance Report\\n\\n\';\n';
  code += '    md += \'**Generated:** \' + new Date().toISOString() + \'\\n\\n\';\n\n';
  code += '    const totalPkgs = results.reduce((sum, r) => sum + r.totalPackages, 0);\n';
  code += '    const totalViolations = results.reduce((sum, r) => sum + r.nonCompliant, 0);\n';
  code += '    const totalReview = results.reduce((sum, r) => sum + r.reviewRequired, 0);\n\n';
  code += '    md += \'## Summary\\n\\n\';\n';
  code += '    md += \'- **Total Packages:** \' + totalPkgs + \'\\n\';\n';
  code += '    md += \'- **Compliant:** \' + (totalPkgs - totalViolations - totalReview) + \'\\n\';\n';
  code += '    md += \'- **Violations:** \' + totalViolations + \'\\n\';\n';
  code += '    md += \'- **Review Required:** \' + totalReview + \'\\n\\n\';\n\n';
  code += '    for (const result of results) {\n';
  code += '      md += \'## \' + result.language + \'\\n\\n\';\n';
  code += '      md += \'- **Total:** \' + result.totalPackages + \'\\n\';\n';
  code += '      md += \'- **Compliant:** \' + result.compliant + \'\\n\';\n';
  code += '      md += \'- **Violations:** \' + result.nonCompliant + \'\\n\';\n';
  code += '      md += \'- **Review Required:** \' + result.reviewRequired + \'\\n\\n\';\n\n';
  code += '      if (result.violations.length > 0) {\n';
  code += '        md += \'### Violations\\n\\n\';\n';
  code += '        for (const vuln of result.violations) {\n';
  code += '          md += \'- **\' + vuln.packageName + \':** \' + vuln.license + \'\\n\';\n';
  code += '        }\n';
  code += '        md += \'\\n\';\n';
  code += '      }\n';
  code += '    }\n\n';
  code += '    return md;\n';
  code += '  }\n\n';
  code += '  private getDefaultPolicy(): CompliancePolicy {\n';
  code += '    return {\n';
  code += '      allowedLicenses: [\'MIT\', \'Apache-2.0\', \'BSD-3-Clause\', \'ISC\'],\n';
  code += '      forbiddenLicenses: [\'GPL-3.0\', \'AGPL-3.0\', \'SSPL\'],\n';
  code += '      reviewRequiredLicenses: [\'LGPL\', \'MPL\', \'CDDL\'],\n';
  code += '      allowPermissive: true,\n';
  code += '      allowCopyleft: false,\n';
  code += '    };\n';
  code += '  }\n';
  code += '}\n\n';
  code += 'const checker = new LicenseComplianceChecker({\n';
  code += '  enableAutoFix: false,\n';
  code += '});\n\n';
  code += 'export default checker;\n';
  code += 'export { LicenseComplianceChecker, LicenseInfo, CompliancePolicy, ComplianceResult };\n';

  return code;
}

export function generatePythonLicense(config: any): string {
  let code = '# Auto-generated License Compliance Checker for ' + config.projectName + '\n';
  code += '# Generated at: ' + new Date().toISOString() + '\n\n';
  code += 'import subprocess\n';
  code += 'import json\n';
  code += 'from pathlib import Path\n';
  code += 'from typing import List, Dict, Optional, Any\n';
  code += 'from dataclasses import dataclass\n';
  code += 'from datetime import datetime\n\n';
  code += '@dataclass\n';
  code += 'class LicenseInfo:\n';
  code += '    package_name: str\n';
  code += '    version: str\n';
  code += '    license: str\n';
  code += '    license_type: str  # "permissive" | "copyleft" | "proprietary" | "unknown"\n';
  code += '    risk: str  # "allowed" | "review-required" | "forbidden"\n\n';
  code += '@dataclass\n';
  code += 'class ComplianceResult:\n';
  code += '    language: str\n';
  code += '    total_packages: int\n';
  code += '    compliant: int\n';
  code += '    non_compliant: int\n';
  code += '    review_required: int\n';
  code += '    violations: List[LicenseInfo]\n';
  code += '    timestamp: str\n\n';
  code += 'class LicenseComplianceChecker:\n';
  code += '    def __init__(self, project_root: str = None, policy: Dict[str, Any] = None, enable_auto_fix: bool = False):\n';
  code += '        self.project_root = Path(project_root or ".")\n';
  code += '        self.policy = policy or self.get_default_policy()\n';
  code += '        self.enable_auto_fix = enable_auto_fix\n\n';
  code += '    async def check_compliance(self) -> List[ComplianceResult]:\n';
  code += '        print("[License] Checking license compliance...")\n';
  code += '        results = []\n\n';
  code += '        # Check npm packages\n';
  code += '        if (self.project_root / "package.json").exists():\n';
  code += '            npm_result = await self.check_npm()\n';
  code += '            if npm_result:\n';
  code += '                results.append(npm_result)\n\n';
  code += '        # Check Python packages\n';
  code += '        if (self.project_root / "requirements.txt").exists() or (self.project_root / "pyproject.toml").exists():\n';
  code += '            pip_result = await self.check_pip()\n';
  code += '            if pip_result:\n';
  code += '                results.append(pip_result)\n\n';
  code += '        # Check Rust packages\n';
  code += '        if (self.project_root / "Cargo.toml").exists():\n';
  code += '            cargo_result = await self.check_cargo()\n';
  code += '            if cargo_result:\n';
  code += '                results.append(cargo_result)\n\n';
  code += '        print("[License] Compliance check complete")\n';
  code += '        return results\n\n';
  code += '    async def check_npm(self) -> Optional[ComplianceResult]:\n';
  code += '        try:\n';
  code += '            print("[License] Checking npm packages...")\n';
  code += '            licenses = await self.get_npm_licenses()\n';
  code += '            return self.evaluate_compliance(licenses, "javascript")\n';
  code += '        except Exception as e:\n';
  code += '            print(f"[License] Failed to check npm licenses: {e}")\n';
  code += '            return None\n\n';
  code += '    async def get_npm_licenses(self) -> List[LicenseInfo]:\n';
  code += '        licenses = []\n\n';
  code += '        try:\n';
  code += '            result = subprocess.run("npm ls --json --depth=0", shell=True, cwd=self.project_root,\n';
  code += '                                        capture_output=True, text=True)\n';
  code += '            data = json.loads(result.stdout)\n';
  code += '            deps = data.get("dependencies", {})\n\n';
  code += '            for name, info in deps.items():\n';
  code += '                pkg = info\n';
  code += '                licenses.append(LicenseInfo(\n';
  code += '                    package_name=name,\n';
  code += '                    version=pkg.get("version", "unknown"),\n';
  code += '                    license=self.extract_license(pkg),\n';
  code += '                    license_type=self.categorize_license(self.extract_license(pkg)),\n';
  code += '                    risk="allowed",\n';
  code += '                ))\n';
  code += '        except Exception as e:\n';
  code += '            # Fallback: parse package.json\n';
  code += '            pkg_path = self.project_root / "package.json"\n';
  code += '            if pkg_path.exists():\n';
  code += '                with open(pkg_path) as f:\n';
  code += '                    pkg = json.load(f)\n';
  code += '                deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}\n';
  code += '                for name in deps:\n';
  code += '                    licenses.append(LicenseInfo(\n';
  code += '                        package_name=name,\n';
  code += '                        version="unknown",\n';
  code += '                        license="unknown",\n';
  code += '                        license_type="unknown",\n';
  code += '                        risk="review-required",\n';
  code += '                    ))\n\n';
  code += '        return licenses\n\n';
  code += '    def extract_license(self, pkg: Dict[str, Any]) -> str:\n';
  code += '        if "license" in pkg:\n';
  code += '            lic = pkg["license"]\n';
  code += '            return lic if isinstance(lic, str) else "unknown"\n';
  code += '        if "licenses" in pkg:\n';
  code += '            return " OR ".join(l.get("type") or l for l in pkg["licenses"])\n';
  code += '        return "unknown"\n\n';
  code += '    def categorize_license(self, license: str) -> str:\n';
  code += '        l = license.lower()\n';
  code += '        permissive = ["mit", "apache", "bsd", "isc", "unlicense"]\n';
  code += '        copyleft = ["gpl", "lgpl", "agpl", "mpl", "cddl", "epl"]\n\n';
  code += '        if any(p in l for p in permissive):\n';
  code += '            return "permissive"\n';
  code += '        if any(c in l for c in copyleft):\n';
  code += '            return "copyleft"\n';
  code += '        if "proprietary" in l or "commercial" in l:\n';
  code += '            return "proprietary"\n';
  code += '        return "unknown"\n\n';
  code += '    async def check_pip(self) -> Optional[ComplianceResult]:\n';
  code += '        try:\n';
  code += '            print("[License] Checking Python packages...")\n';
  code += '            licenses = await self.get_pip_licenses()\n';
  code += '            return self.evaluate_compliance(licenses, "python")\n';
  code += '        except Exception as e:\n';
  code += '            print(f"[License] Failed to check pip licenses: {e}")\n';
  code += '            return None\n\n';
  code += '    async def get_pip_licenses(self) -> List[LicenseInfo]:\n';
  code += '        licenses = []\n';
  code += '        req_path = self.project_root / "requirements.txt"\n\n';
  code += '        if not req_path.exists():\n';
  code += '            return licenses\n\n';
  code += '        with open(req_path) as f:\n';
  code += '            lines = [l.strip() for l in f.readlines() if l.strip() and not l.startswith("#")]\n\n';
  code += '        for line in lines:\n';
  code += '            import re\n';
  code += '            match = re.match(r"^([a-zA-Z0-9_-]+)(==|>=|<=)(.+)$", line)\n';
  code += '            if match:\n';
  code += '                name, _, version = match.groups()\n';
  code += '                licenses.append(LicenseInfo(\n';
  code += '                    package_name=name,\n';
  code += '                    version=version,\n';
  code += '                    license="unknown",\n';
  code += '                    license_type="unknown",\n';
  code += '                    risk="review-required",\n';
  code += '                ))\n\n';
  code += '        return licenses\n\n';
  code += '    async def check_cargo(self) -> Optional[ComplianceResult]:\n';
  code += '        try:\n';
  code += '            print("[License] Checking Rust packages...")\n';
  code += '            licenses = await self.get_cargo_licenses()\n';
  code += '            return self.evaluate_compliance(licenses, "rust")\n';
  code += '        except Exception as e:\n';
  code += '            print(f"[License] Failed to check cargo licenses: {e}")\n';
  code += '            return None\n\n';
  code += '    async def get_cargo_licenses(self) -> List[LicenseInfo]:\n';
  code += '        licenses = []\n';
  code += '        cargo_path = self.project_root / "Cargo.toml"\n\n';
  code += '        if not cargo_path.exists():\n';
  code += '            return licenses\n\n';
  code += '        with open(cargo_path) as f:\n';
  code += '            content = f.read()\n\n';
  code += '        import re\n';
  code += '        deps_match = re.search(r"\\[dependencies\\]([\\s\\S]*?)(?=\\[|$)", content)\n\n';
  code += '        if deps_match:\n';
  code += '            deps = deps_match.group(1)\n';
  code += '            lines = [l for l in deps.split("\\n") if "=" in l]\n\n';
  code += '            for line in lines:\n';
  code += '                match = re.match(r"^([a-zA-Z0-9_-]+)\\s*=\\s*\\"(.+)\\"", line)\n';
  code += '                if match:\n';
  code += '                    name, version = match.groups()\n';
  code += '                    licenses.append(LicenseInfo(\n';
  code += '                        package_name=name,\n';
  code += '                        version=version,\n';
  code += '                        license="unknown",\n';
  code += '                        license_type="unknown",\n';
  code += '                        risk="review-required",\n';
  code += '                    ))\n\n';
  code += '        return licenses\n\n';
  code += '    def evaluate_compliance(self, licenses: List[LicenseInfo], language: str) -> ComplianceResult:\n';
  code += '        violations = []\n';
  code += '        compliant = 0\n';
  code += '        review_required = 0\n\n';
  code += '        for lic in licenses:\n';
  code += '            lic.risk = self.assess_risk(lic)\n';
  code += '            if lic.risk == "forbidden":\n';
  code += '                violations.append(lic)\n';
  code += '            elif lic.risk == "review-required":\n';
  code += '                review_required += 1\n';
  code += '            else:\n';
  code += '                compliant += 1\n\n';
  code += '        return ComplianceResult(\n';
  code += '            language=language,\n';
  code += '            total_packages=len(licenses),\n';
  code += '            compliant=compliant,\n';
  code += '            non_compliant=len(violations),\n';
  code += '            review_required=review_required,\n';
  code += '            violations=violations,\n';
  code += '            timestamp=datetime.now().isoformat(),\n';
  code += '        )\n\n';
  code += '    def assess_risk(self, lic: LicenseInfo) -> str:\n';
  code += '        license = lic.license.lower()\n\n';
  code += '        # Check forbidden licenses\n';
  code += '        for forbidden in self.policy.get("forbiddenLicenses", []):\n';
  code += '            if forbidden.lower() in license:\n';
  code += '                return "forbidden"\n\n';
  code += '        # Check review-required licenses\n';
  code += '        for review in self.policy.get("reviewRequiredLicenses", []):\n';
  code += '            if review.lower() in license:\n';
  code += '                return "review-required"\n\n';
  code += '        # Check by license type\n';
  code += '        if lic.license_type == "copyleft" and not self.policy.get("allowCopyleft", False):\n';
  code += '            return "review-required"\n\n';
  code += '        if lic.license_type == "unknown":\n';
  code += '            return "review-required"\n\n';
  code += '        return "allowed"\n\n';
  code += '    async def fix_violations(self, results: List[ComplianceResult]) -> None:\n';
  code += '        if not self.enable_auto_fix:\n';
  code += '            print("[License] Auto-fix is disabled")\n';
  code += '            return\n\n';
  code += '        print("[License] Cannot automatically fix license violations")\n';
  code += '        print("[License] Please manually review and replace forbidden packages")\n\n';
  code += '    async def generate_report(self, results: List[ComplianceResult]) -> None:\n';
  code += '        print("[License] Generating compliance report...")\n\n';
  code += '        report_path = self.project_root / "license-compliance-report.json"\n';
  code += '        with open(report_path, "w") as f:\n';
  code += '            json.dump([{\n';
  code += '                "language": r.language,\n';
  code += '                "totalPackages": r.total_packages,\n';
  code += '                "compliant": r.compliant,\n';
  code += '                "nonCompliant": r.non_compliant,\n';
  code += '                "reviewRequired": r.review_required,\n';
  code += '                "violations": [{\n';
  code += '                    "packageName": v.package_name,\n';
  code += '                    "version": v.version,\n';
  code += '                    "license": v.license,\n';
  code += '                    "licenseType": v.license_type,\n';
  code += '                    "risk": v.risk,\n';
  code += '                } for v in r.violations],\n';
  code += '                "timestamp": r.timestamp,\n';
  code += '            } for r in results], f, indent=2)\n\n';
  code += '        # Generate markdown\n';
  code += '        md_report = self.generate_markdown_report(results)\n';
  code += '        md_path = self.project_root / "license-compliance-report.md"\n';
  code += '        with open(md_path, "w") as f:\n';
  code += '            f.write(md_report)\n\n';
  code += '        print(f"[License] Report saved to {report_path}")\n\n';
  code += '    def generate_markdown_report(self, results: List[ComplianceResult]) -> str:\n';
  code += '        md = "# License Compliance Report\\n\\n"\n';
  code += '        md += f"**Generated:** {datetime.now().isoformat()}\\n\\n"\n\n';
  code += '        total_pkgs = sum(r.total_packages for r in results)\n';
  code += '        total_violations = sum(r.non_compliant for r in results)\n';
  code += '        total_review = sum(r.review_required for r in results)\n\n';
  code += '        md += "## Summary\\n\\n"\n';
  code += '        md += f"- **Total Packages:** {total_pkgs}\\n"\n';
  code += '        md += f"- **Compliant:** {total_pkgs - total_violations - total_review}\\n"\n';
  code += '        md += f"- **Violations:** {total_violations}\\n"\n';
  code += '        md += f"- **Review Required:** {total_review}\\n\\n"\n\n';
  code += '        for result in results:\n';
  code += '            md += f"## {result.language}\\n\\n"\n';
  code += '            md += f"- **Total:** {result.total_packages}\\n"\n';
  code += '            md += f"- **Compliant:** {result.compliant}\\n"\n';
  code += '            md += f"- **Violations:** {result.non_compliant}\\n"\n';
  code += '            md += f"- **Review Required:** {result.review_required}\\n\\n"\n\n';
  code += '            if result.violations:\n';
  code += '                md += "### Violations\\n\\n"\n';
  code += '                for vuln in result.violations:\n';
  code += '                    md += f"- **{vuln.package_name}:** {vuln.license}\\n"\n';
  code += '                md += "\\n"\n\n';
  code += '        return md\n\n';
  code += '    def get_default_policy(self) -> Dict[str, Any]:\n';
  code += '        return {\n';
  code += '            "allowedLicenses": ["MIT", "Apache-2.0", "BSD-3-Clause", "ISC"],\n';
  code += '            "forbiddenLicenses": ["GPL-3.0", "AGPL-3.0", "SSPL"],\n';
  code += '            "reviewRequiredLicenses": ["LGPL", "MPL", "CDDL"],\n';
  code += '            "allowPermissive": True,\n';
  code += '            "allowCopyleft": False,\n';
  code += '        }\n\n';
  code += 'checker = LicenseComplianceChecker(\n';
  code += '    enable_auto_fix=False,\n';
  code += ')\n';

  return code;
}

export async function writeFiles(
  config: any,
  outputDir: string
): Promise<void> {
  const fs = await import('fs');
  const path = await import('path');

  // Create output directory
  fs.mkdirSync(outputDir, { recursive: true });

  // Generate TypeScript version
  const tsCode = generateTypeScriptLicense(config);
  const tsPath = path.join(outputDir, 'license-compliance.ts');
  fs.writeFileSync(tsPath, tsCode);

  // Generate Python version
  const pyCode = generatePythonLicense(config);
  const pyPath = path.join(outputDir, 'license-compliance.py');
  fs.writeFileSync(pyPath, pyCode);

  // Generate documentation
  const md = generateLicenseMD(config);
  const mdPath = path.join(outputDir, 'LICENSE_COMPLIANCE.md');
  fs.writeFileSync(mdPath, md);

  // Generate package.json for TypeScript
  const packageJson = {
    name: config.projectName.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    description: 'Unified license compliance checker',
    main: 'license-compliance.ts',
    scripts: {
      test: 'echo "Error: no test specified" && exit 1',
    },
    dependencies: {},
    devDependencies: {
      '@types/node': '^20.0.0',
    },
  };
  const pkgPath = path.join(outputDir, 'package.json');
  fs.writeFileSync(pkgPath, JSON.stringify(packageJson, null, 2));

  // Generate requirements.txt for Python
  const requirements = [];
  const reqPath = path.join(outputDir, 'requirements.txt');
  fs.writeFileSync(reqPath, requirements.join('\n') + '\n');

  // Generate config file
  const configJson = {
    projectName: config.projectName,
    enableAutoFix: config.enableAutoFix,
    policy: config.policy || {},
    generatedAt: new Date().toISOString(),
  };
  const cfgPath = path.join(outputDir, 'license-config.json');
  fs.writeFileSync(cfgPath, JSON.stringify(configJson, null, 2));
}
